export const exerciseImages: Partial<Record<string, number>> = {
  "ab-wheel-rollout": require("../../../assets/exercises/ab-wheel-rollout.png"),
  "back-widows": require("../../../assets/exercises/back-widows.png"),
  "barbell-bench-press": require("../../../assets/exercises/barbell-bench-press.png"),
  "barbell-bent-over-row": require("../../../assets/exercises/barbell-bent-over-row.png"),
  "barbell-curl": require("../../../assets/exercises/barbell-curl.png"),
  "barbell-deadlift": require("../../../assets/exercises/barbell-deadlift.png"),
  "barbell-squat": require("../../../assets/exercises/barbell-squat.png"),
  "bench-step-up": require("../../../assets/exercises/bench-step-up.png"),
  "bird-dog": require("../../../assets/exercises/bird-dog.png"),
  "bodyweight-squat": require("../../../assets/exercises/bodyweight-squat.png"),
  "brisk-walk-or-incline-walk": require("../../../assets/exercises/brisk-walk-or-incline-walk.png"),
  "cable-crunch": require("../../../assets/exercises/cable-crunch.png"),
  "cable-woodchop": require("../../../assets/exercises/cable-woodchop.png"),
  "cardio-intervals": require("../../../assets/exercises/cardio-intervals.png"),
  "chest-dips": require("../../../assets/exercises/chest-dips.png"),
  "chest-fly": require("../../../assets/exercises/chest-fly.png"),
  "clean-and-press": require("../../../assets/exercises/clean-and-press-barbell.png"),
  "close-grip-bench-press": require("../../../assets/exercises/close-grip-bench-press.png"),
  "crunch": require("../../../assets/exercises/crunch.png"),
  "decline-bench-press": require("../../../assets/exercises/decline-bench-press.png"),
  "decline-crunch": require("../../../assets/exercises/decline-crunch.png"),
  "decline-sit-up": require("../../../assets/exercises/decline-sit-up.png"),
  "dead-bug": require("../../../assets/exercises/dead-bug.png"),
  "dragon-flag": require("../../../assets/exercises/dragon-flag.png"),
  "dumbbell-bench-press": require("../../../assets/exercises/dumbbell-bench-press.png"),
  "dumbbell-pullover": require("../../../assets/exercises/dumbbell-pullover.png"),
  "dumbbell-romanian-deadlift": require("../../../assets/exercises/dumbbell-romanian-deadlift.png"),
  "dumbbell-shoulder-press": require("../../../assets/exercises/dumbbell-shoulder-press.png"),
  "farmer-hold": require("../../../assets/exercises/farmer-hold.png"),
  "front-squat": require("../../../assets/exercises/front-squat.png"),
  "front-raise": require("../../../assets/exercises/dumbbell-front-raise.png"),
  "glute-bridge": require("../../../assets/exercises/glute-bridge.png"),
  "good-morning": require("../../../assets/exercises/good-morning-barbell.png"),
  "goblet-squat": require("../../../assets/exercises/goblet-squat.png"),
  "hanging-knee-raise": require("../../../assets/exercises/hanging-knee-raise.png"),
  "hanging-leg-raise": require("../../../assets/exercises/hanging-leg-raise.png"),
  "hanging-oblique-raise": require("../../../assets/exercises/hanging-oblique-knee-raise.png"),
  "hip-hinge-drill": require("../../../assets/exercises/hip-hinge-drill.png"),
  "hollow-hold": require("../../../assets/exercises/hollow-hold.png"),
  "incline-bench-press": require("../../../assets/exercises/incline-bench-press.png"),
  "incline-dumbbell-curl": require("../../../assets/exercises/incline-dumbbell-curl.png"),
  "incline-push-up": require("../../../assets/exercises/incline-push-up.png"),
  "kettlebell-deadlift": require("../../../assets/exercises/kettlebell-deadlift.png"),
  "kettlebell-floor-press": require("../../../assets/exercises/kettlebell-floor-press.png"),
  "kettlebell-front-squat": require("../../../assets/exercises/kettlebell-front-squat.png"),
  "kettlebell-row": require("../../../assets/exercises/kettlebell-row.png"),
  "kettlebell-swing-finisher": require("../../../assets/exercises/kettlebell-swing-finisher.png"),
  "laying-leg-raise": require("../../../assets/exercises/laying-leg-raise.png"),
  "landmine-twist": require("../../../assets/exercises/landmine-twist.png"),
  "lat-pulldown": require("../../../assets/exercises/lat-pulldown-cable.png"),
  "lateral-raise": require("../../../assets/exercises/dumbbell-lateral-raise.png"),
  "leg-curl": require("../../../assets/exercises/leg-curl-machine.png"),
  "leg-extension": require("../../../assets/exercises/leg-extension-machine.png"),
  "low-impact-bodyweight-circuit": require("../../../assets/exercises/low-impact-bodyweight-circuit.png"),
  "march-in-place-finisher": require("../../../assets/exercises/march-in-place-finisher.png"),
  "medicine-ball-sit-up": require("../../../assets/exercises/medicine-ball-sit-up.png"),
  "overhead-tricep-extension": require("../../../assets/exercises/overhead-tricep-extension.png"),
  "pike-push-up": require("../../../assets/exercises/pike-push-up.png"),
  "plank": require("../../../assets/exercises/plank.png"),
  "prone-y-t-w-raises": require("../../../assets/exercises/prone-y-t-w-raises.png"),
  "push-up": require("../../../assets/exercises/push-up.png"),
  "resistance-band-chest-press": require("../../../assets/exercises/resistance-band-chest-press.png"),
  "resistance-band-row": require("../../../assets/exercises/resistance-band-row.png"),
  "reverse-fly": require("../../../assets/exercises/dumbbell-reverse-fly.png"),
  "reverse-lunge": require("../../../assets/exercises/reverse-lunge.png"),
  "romanian-deadlift": require("../../../assets/exercises/romanian-deadlift.png"),
  "russian-twist": require("../../../assets/exercises/russian-twist.png"),
  "shadow-boxing-intervals": require("../../../assets/exercises/shadow-boxing-intervals.png"),
  "side-plank": require("../../../assets/exercises/side-plank.png"),
  "side-plank-hip-dip": require("../../../assets/exercises/side-plank-hip-dip.png"),
  "single-arm-dumbbell-row": require("../../../assets/exercises/single-arm-dumbbell-row.png"),
  "single-leg-glute-bridge": require("../../../assets/exercises/single-leg-glute-bridge.png"),
  "skullcrusher": require("../../../assets/exercises/skullcrusher.png"),
  "slow-mountain-climber": require("../../../assets/exercises/slow-mountain-climber.png"),
  "split-squat": require("../../../assets/exercises/split-squat.png"),
  "standing-chest-fly": require("../../../assets/exercises/standing-chest-fly.png"),
  "step-up": require("../../../assets/exercises/step-up.png"),
  "straight-leg-deadlift": require("../../../assets/exercises/straight-leg-deadlift-barbell.png"),
  "upright-row": require("../../../assets/exercises/barbell-upright-row.png"),
  "wrist-curl-down": require("../../../assets/exercises/wrist-curl-palms-down.png"),
  "wrist-curl-up": require("../../../assets/exercises/wrist-curl-palms-up.png"),
  "assisted-pull-up-or-chin-up": require("../../../assets/exercises/close-grip-chin-up.png"),
  "calf-raise": require("../../../assets/exercises/standing-calf-raise-machine.png"),
  "wide-grip-pull-up": require("../../../assets/exercises/wide-grip-pull-ups.png"),
  "toes-to-bar": require("../../../assets/exercises/toes-to-bar.png"),
};

const exerciseImageSlugAliases: Partial<Record<string, string>> = {
  "barbell-back-squat": "barbell-squat",
  "wide-grip-pull-ups": "assisted-pull-up-or-chin-up",
  "hanging-oblique-knee-raise": "hanging-oblique-raise",
  "standing-calf-raise": "calf-raise",
  "donkey-calf-raise": "calf-raise",
};

export function getExerciseImageForSlug(slug: string) {
  const directMatch = exerciseImages[slug];

  if (directMatch) {
    return directMatch;
  }

  const aliasSlug = exerciseImageSlugAliases[slug];
  return aliasSlug ? exerciseImages[aliasSlug] : undefined;
}
